proxy:
  hostname: birkas_orsi-proxy
  image: birkas_orsi-base
  command: start
  volumes_from:
      - birkas_orsi-data
  entrypoint: ['python3', '/config/run.py']

postgres:
    hostname: birkas_orsi-postgres
    image: birkas_orsi-postgres
    command: start
    volumes_from:
        - proxy
    volumes:
        - "./docker/postgres/config:/config"
        - "./container_shared:/container_shared"
    log_opt:
        max-size: "5m"
        max-file: "1"
    entrypoint: ['python3', '/config/run.py']
    environment:
        PGDATA: /data/postgres
    env_file: env.txt
    ports:
        - "5433:5432"

django:
    hostname: birkas_orsi-django
    image: birkas_orsi-django-python3
    entrypoint: ['python3', '/config/run.py']
    command: start_runserver
    volumes_from:
        - proxy
    volumes:
        - "./src:/src"
        - "./docker/django-python3/config:/config"
        - "./container_shared:/container_shared"
    links:
        - "postgres:postgres"
    log_opt:
        max-size: "5m"
        max-file: "1"
    environment:
        PYTHONPATH: /src
        DJANGO_SETTINGS_MODULE: core.settings
        PYTHONUNBUFFERED: "true"
    env_file: env.txt
    ports:
        - "80:8000"

nodejs:
    hostname: birkas_orsi-nodejs
    image: birkas_orsi-nodejs
    command: start_watchify
    volumes_from:
        - proxy
    volumes:
        - "./docker/nodejs/config:/config"
        - "./container_shared:/container_shared"
        - "./react:/react"
        - "./src:/src"
    log_opt:
        max-size: "5m"
        max-file: "1"
    entrypoint: ['python3', '/config/run.py']
    env_file: env.txt