# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:57
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='avatars'),
        ),
    ]
