# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pdf',
            field=models.FileField(null=True, upload_to=job.models.job_pdf_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=job.models.job_image_path),
        ),
    ]
