# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import job.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20160320_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=job.models.job_pdf_path),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.Category'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='job.Job'),
        ),
    ]
